Repository emilnymann/1AarsProjekt, pull requests merged in 2020-05, with the labels that each got.

#12 Merge opdateret readme
  README.md
Labels: documentation

#14 Merge Metrikker.doc
  Metrikker.doc
Labels: project management

#26 Merge omdøb projektplan i readme
  README.md
Labels: documentation

#35 Opdater readme med manglende info i beskrivelse
  README.md
Labels: documentation

#34 Merge UC01 Åbn Beskeder
  02 Requirements & Analysis/UC01 åbn beskeder.docx
Labels: uml

#36 Merge UC02 Send besked.docx
  02 Requirements & Analysis/UC02 Send besked.docx
Labels: uml

#39 Merge UC02 send beskeder
  02 Requirements & Analysis/UC02 Send besked.docx
Labels: uml

#37 Merge AD01 Åbn beskeder
  02 Requirements & Analysis/AD01 Åbn beskeder.vsdx
Labels: uml

#41 Merge DOM02 Send besked
  01 Business Modeling/DOM02 Send besked.vsdx
Labels: uml

#44 Merge SSD01 Åbn beskeder
  02 Requirements & Analysis/SSD01 Åbn beskeder.vsdx
Labels: uml

#46 Merge SSD02 Send besked
  02 Requirements & Analysis/SSD02 Send besked.vsdx
Labels: uml

#56 Merge Android Studio projekt-filer
  04 Implementation/.gitignore
  04 Implementation/.idea/.name
  04 Implementation/.idea/codeStyles/Project.xml
  04 Implementation/.idea/gradle.xml
  04 Implementation/.idea/misc.xml
  04 Implementation/.idea/runConfigurations.xml
  04 Implementation/.idea/vcs.xml
  04 Implementation/app/.gitignore
  04 Implementation/app/build.gradle
  04 Implementation/app/proguard-rules.pro
  04 Implementation/app/src/androidTest/java/dk/frbsportgruppe1/frbsport/ExampleInstrumentedTest.java
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  04 Implementation/app/src/main/res/drawable/ic_launcher_background.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/styles.xml
  04 Implementation/app/src/test/java/dk/frbsportgruppe1/frbsport/ExampleUnitTest.java
  04 Implementation/build.gradle
  04 Implementation/gradle.properties
  04 Implementation/gradle/wrapper/gradle-wrapper.jar
  04 Implementation/gradle/wrapper/gradle-wrapper.properties
  04 Implementation/gradlew
  04 Implementation/gradlew.bat
  04 Implementation/settings.gradle
Labels: project management

#74 Merge uc01 vis beskedhistorik
  02 Requirements & Analysis/UC01 Vis beskedhistorik.docx
Labels: uml

#79 Merge rettet DOM01 vis beskedhistorik
  01 Business Modeling/DOM01 Vis beskedhistorik.vsdx
Labels: uml

#81 Merge Rettet SSD02 Send besked
  02 Requirements & Analysis/SSD02 Send besked.vsdx
Labels: uml

#116 Merge OC0101 visBeskedhistorik
  02 Requirements & Analysis/OC0101 visBeskedhistorik.docx
Labels: uml

#132 Merge OC02 sendBesked
  02 Requirements & Analysis/OC02 sendBesked.docx
Labels: uml, uml change

#141 Merge SD0102 og DCD0102 visPatientoversigt
  03 Design/DCD0102 visPatientoversigt.vsdx
  03 Design/SD0102 visPatientoversigt.vsdx
Labels: uml

#254 Merge OC0301
  02 Requirements & Analysis/OC0301 showCalender.docx
Labels: uml

#255 Merge OC05 showWorkoutplan
  02 Requirements & Analysis/OC05 showWorkoutplan.docx
Labels: uml
